const EMAILJS_USERID: any = process.env.REACT_APP_EMAILJS_USERID;
const EMAILJS_TEMPLATEID: any  = process.env.REACT_APP_EMAILJS_TEMPLATEID;
const EMAILJS_SERVICEID: any  = process.env.REACT_APP_EMAILJS_SERVICEID;

export {
    EMAILJS_USERID,
    EMAILJS_TEMPLATEID,
    EMAILJS_SERVICEID
};